from tkinter import *
def Binary():
      a=t1.get()
      a=int(a)
      c=bin(a)
      t2.delete(0,END)
      t2.insert(0,c)
def Octal():
      a=t1.get()
      a=int(a)
      c=oct(a)
      t2.delete(0,END)
      t2.insert(0,c)
def hexadecimal():
      a=t1.get()
      a=int(a)
      c=hex(a)
      t2.delete(0,END)
      t2.insert(0,c)
window=Tk()
window.geometry("500x500")
l1=Label(window,text="Enter Number")
l2=Label(window,text="Ans")
t1=Entry(window)
t2=Entry(window)
b1=Button(window,text="Binary",command=Binary)
b2=Button(window,text="Octal",command=Octal)
b3=Button(window,text="hexadecimal",command=hexadecimal)
l1.grid(row=0,column=0)
t1.grid(row=0,column=1)
l2.grid(row=1,column=0)
t2.grid(row=1,column=1)
b1.grid(row=2,column=0)
b2.grid(row=2,column=1)
b3.grid(row=2,column=2)
